### ISSUE TITLE
ModuleNotFoundError: No module named 'mlx'

### ISSUE THREAD

**Issue by emekaokoye** [OoriData/Toolio#22]
Toolio installed successfully on my Windows 11 8GB machine.

I ran this command "toolio_server --model=distilbert/distilgpt2" on the command prompt and got "ModuleNotFoundError: No module named 'mlx'".

I tried installing "mlx" but got:
```
ERROR: Could not find a version that satisfies the requirement mlx (from versions: none)
ERROR: No matching distribution found for mlx
```

What does  these errors mean? What have i done wrong?
![error](https://github.com/user-attachments/assets/72165fc1-1f84-499a-b1c8-946c888221c0)

**Comment by uogbuji** [comment]
Unfortunately, you can't run Toolio on Windows, because you can't run MLX  on Windows. MLX uses C integration with Metal on Apple Silicon. Sorry about that, but it's always been M1/M2/M3/M4 Mac only.

I do appreciate your interest, though! Maybe I'll try to figure out how to run Toolio in a GitHub Mac CI-runner.

**Comment by emekaokoye** [comment]
Thanks.

**Comment by uogbuji** [comment]
@emekaokoye BTW I made some changes to make this situation less confusing in future. So if I try to use Toolio on a Linux box:

```sh
$ pip install git+https://github.com/OoriData/Toolio@main
$ python -c "import toolio"
/opt/mlai/pyvenv/test/lib/python3.11/site-packages/toolio/__init__.py:45: UserWarning: Unable to import MLX. You will only be able to run pure HTTP client components.
  warnings.warn('Unable to import MLX, which requires an Apple Silicon Mac. You will only be able to run pure HTTP client components.')
```
